### ISSUE TITLE
Quite OK Audio (QOA) Decoder component for foobar2000 v2 x64

### ISSUE THREAD

**Issue by Barough** [pfusik/qoa-ci#1]
Any chance you could update your Decoder component to support foobar2000 v2 x64?

**Comment by pfusik** [comment]
Sure, it's only a matter of build scripts.
foobar2000 v2 is still in beta, right? Do you know when it's going to be released officially?

**Comment by Barough** [comment]
v2 is still in Beta. Dont have a clue when v2 will be out of beta. Still a lot of fixes being done to it. You need to check with Peter regarding where v2 currently stands.

**Comment by pfusik** [comment]
Released at https://www.foobar2000.org/components/view/foo_qoa as 0.3.0. The change in the foobar2000 component is the x64 compatibility.

BTW. I'd like to add encoding in foobar2000, but I don't know how. I got no answer at https://hydrogenaud.io/index.php/topic,123687.new.html#new Can you help?

**Comment by Barough** [comment]
Thnx a lot for the updated component. :)

You add new encoders through the Converter Setup in fb2k. ATM so is there not easy access to the Converter Setup in the menus. 

Add a song to the Default Playlist in fb2k. Right-click on it, the go to Convert and click on the 3 dots (...) at the bottom. 
1 - Click on/Mark [default] in the left column
2 - Click on Output format on the right side
3 - Click 'Add New'.
3.1 - In the New Preset window, under Encoder, select Custom
3.2 - Add all required info for the Encoder and then click OK and then Back.
3.3 - Click on [default]. The default preset now contain all the info for the encoder you added. 
3.4 - Now Click on 'Save' -> Create new Preset

**Comment by pfusik** [comment]
Thanks! Encoding works using your instructions and these settings:

![image](https://user-images.githubusercontent.com/351822/229747540-87e53451-20e2-4eda-ad46-8454344bf608.png)

Also need to uncheck "Transfer metadata (tags)" and "Transfer attached pictures" because QOA doesn't support that.

**Comment by Barough** [comment]
Great to hear that you got it working. :)

**Comment by Barough** [comment]
> foobar2000 v2 is still in beta, right? Do you know when it's going to be released officially?

Beta 33 that just was released is a Release candidate build.
https://wiki.hydrogenaud.io/index.php?title=Foobar2000:Version_2.0_Beta_Change_Log

**Comment by pfusik** [comment]
Thanks for info!
